services: 
  db_valex_test:
    image: postgres
    container_name: db_valex_test
    restart: always
    ports: 
      - 5430:5432
    env_file:
      - .env.test
    volumes:
      - postgres_test:/var/lib/postgresql/data
  
  node_app_valex_test:
    build: 
      context: .
      dockerfile: Dockerfile.test
    container_name: node_app_valex_test
    ports: 
      - 5000:5000
    depends_on:
      - db_valex_test
    env_file:
      - .env.test
    working_dir: /usr/src/valex
    command: bash -c "prisma migrate dev && npx prisma db seed && npm run test"
    volumes:
      - ./src:/usr/src/valex/src
      - ./prisma:/usr/src/valex/prisma
      - ./tests:/usr/src/valex/tests
      - ./.env.test:/usr/src/valex/.env.test
      - ./.eslintrc.json:/usr/src/valex/.eslintrc.json
      - ./.prettierrc:/usr/src/valex/.prettierrc
      - ./tsconfig.eslint.json:/usr/src/valex/tsconfig.eslint.json
      - ./tsconfig.json:/usr/src/valex/tsconfig.json
      - ./package.json:/usr/src/valex/package.json
      - ./package-lock.json:/usr/src/valex/package-lock.json    
  
volumes:
  postgres_test: